### PR TITLE
Feature/letter spacing

### PR DESCRIPTION
**Pull request by perruche**
- Add a map to handle `letter-spacing`, in order to have custom ones, or zero `letter-spacing` classes.
- Remove the default `font-family` assignement to `body` and `hn` which often need an override, I do not think this is the scope of the toolkit, thoughts on this ?

### CODE REVIEW

**Review by titouanmathis — APPROVED** [review]
👍 

I added an NPM script to fix files with Stylelint. 
This is a small feature, so I will merge it directly.

**Comment by titouanmathis** [comment]
Closes #12

**Comment by perruche** [comment]
> I added an NPM script to fix files with Stylelint.

This makes me think we should add a "How to contribute" section on readme. And maybe split each task in a dedicated page ?

**Comment by titouanmathis** [comment]
@perruche I added a small "[Contributing](https://github.com/studiometa/scss-toolkit/tree/develop#contributing)" section on `develop` (see 04a0702), it will be published on `master` with the 1.2.0 release 😉 

> And maybe split each task in a dedicated page ?

Dedicated page for documentation? Or for the contributing guide?

**Comment by perruche** [comment]
nevermind i got confused.

**Pull request merged**
